config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#landing'
  get 'calendar', to: 'pages#calendar'
  get 'profile/:id', to: 'extras#profile'
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :password_resets, only: %i[new create edit update]

  get '/help', to: 'pages#help'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # get 'users/index/:id', to: 'users#index'
  get '/ranking/:id', to: 'users#ranking'
  get '/users/edit', to: 'users#edit'
  resources :users, except: [:index] do
    member do
      get :lessons
    end
  end

  get '/lessons/:id', to: 'lessons#index'
for i in (1..20)
  get "/lessons/:id/#{i}", to: "lessons#lesson#{i}"
end
  resources :lessons
  resources :account_activations, only: [:edit]
  resources :successes, only: %i[create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
before_action :get_user, only: [:edit, :update]
before_action :valid_user, only: [:edit, :update]
before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "パスワードをリセットしました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "パスワード再設定のメールが送信されました"
      redirect_to root_url
    else
      flash.now[:danger] = "メールアドレスが見つかりません"
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        flash[:danger] = "正しいユーザーではありません"
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "有効期限が切れています"
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "新規登録") %>
<% provide(:css, (stylesheet_link_tag 'bootstrap.min',
                                      'icons',
                                      'style.css')) %>
<% provide(:js1, (javascript_include_tag 'modernizr.min')) %>

<div class="account-pages"></div>
<div class="clearfix"></div>
<div class="wrapper-page">
  <div class="text-center">
    <%= link_to '/', class: 'logo' do %>
      <span>Pian<span>ist</span></span>
    <% end %>
    <h5 class="text-muted m-t-0 font-600">作曲とピアノの学習サービス</h5>
  </div>
  <div class="m-t-20">
    <%= render 'shared/error_messages' %>
  </div>
  <div class="m-t-40 card-box">
    <div class="text-center">
      <h4 class="text-uppercase font-bold m-b-0">パスワード再設定</h4>
    </div>
    <div class="p-20">
      <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
        <form class="form-horizontal m-t-20">

          <%= hidden_field_tag :email, @user.email %>

					<div class="form-group">
						<div class="col-xs-12">
              <%= f.password_field :password, class: "form-control", placeholder:"新しいパスワード" %>
								<!-- <input class="form-control" type="password" required="" placeholder="Password"> -->
						</div>
					</div>

          <div class="form-group">
            <div class="col-xs-12">
              <%= f.password_field :password_confirmation, class: "form-control", placeholder:"パスワード確認" %>
                <!-- <input class="form-control" type="password" required="" placeholder="Password"> -->
            </div>
          </div>

					<div class="form-group text-center m-t-40">
						<div class="col-xs-12">
              <%= f.submit "パスワードを更新する", class: "btn btn-custom btn-bordred btn-block" %>
							<!-- <button class="btn btn-custom btn-bordred btn-block waves-effect waves-light" type="submit">
								Register
							</button> -->
            </div>
          </div>
				</form>
      <% end %>
    </div>
  </div>
          <!-- end card-box -->
<% provide(:js2, (javascript_include_tag 'jquery.min',
                                         'popper.min',
                                         'bootstrap.min',
                                         'detect',
                                         'fastclick',
                                         'jquery.blockUI',
                                         'waves',
                                         'jquery.nicescroll',
                                         'jquery.slimscroll',
                                         'jquery.scrollTo.min',
                                         'jquery.core',
                                         'jquery.app')) %>

app/views/password_resets/new.html.erb
<% provide(:title, "パスワードリセット") %>
<% provide(:css, (stylesheet_link_tag 'bootstrap.min',
                                      'icons',
                                      'style.css')) %>
<% provide(:js1, (javascript_include_tag 'modernizr.min')) %>


<div class="account-pages"></div>
<div class="clearfix"></div>
<div class="wrapper-page">
  <div class="text-center">
    <%= link_to '/', class: 'logo' do %>
    <span>Pian<span>ist</span></span>
    <% end %>
    <h5 class="text-muted m-t-0 font-600">作曲とピアノの学習サービス</h5>
  </div>
  <div class="m-t-20">
    <%= render 'shared/alert' %>
  </div>
  <div class="m-t-40 card-box">
    <div class="text-center">
      <h4 class="text-uppercase font-bold m-b-0">パスワードリセット</h4>

      <p class="text-muted m-b-0 font-13 m-t-20"> 登録しているメールアドレスを入力してください。<br>
        パスワードを再設定する手順を記載したメールが送信されます。 </p>
    </div>
    <div class="p-20">
      <%= form_for :password_reset, url: password_resets_path, class: 'form-horizontal m-t-20' do |f| %>

      <div class="form-group">
        <div class="col-xs-12">
          <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
        </div>
      </div>

      <div class="form-group text-center m-t-20 m-b-0">
        <div class="col-xs-12">
          <%= f.submit "送信する", class: "btn btn-custom btn-bordred btn-block" %>
        </div>
      </div>

      <% end %>
      <!-- </form> -->
    </div>
  </div>
  <!-- end card-box-->

  <div class="row">
    <div class="col-sm-12 text-center">
      <p class="text-muted">アカウントを持っている方は
        <%= link_to login_path, class: 'text-primary m-l-5' do %>
        <b>こちらでログイン！</b>
        <% end %>
      </p>
    </div>
  </div>
</div>
<% provide(:js2, (javascript_include_tag 'jquery.min',
                                                 'popper.min',
                                                 'bootstrap.min',
                                                 'detect',
                                                 'fastclick',
                                                 'jquery.blockUI',
                                                 'waves',
                                                 'jquery.nicescroll',
                                                 'jquery.slimscroll',
                                                 'jquery.scrollTo.min',
                                                 'jquery.core',
                                                 'jquery.app')) %>